import './globals.css';
import Sidebar from '../components/Sidebar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <Sidebar>
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
